config/routes.rb
Rails.application.routes.draw do
  match "/" => redirect("/login"), via:[:get]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # resources :admins

  namespace :admin do
      resources :students, only: [:new, :create, :index, :edit, :update, :destroy, :show]
      resources :instructors, only: [:new, :create, :edit, :update, :destroy, :index, :show]
      resources :cohorts, only: [:new, :create, :edit, :update, :destroy, :index, :show]
      resources :courses, only: [:new, :create, :edit, :update, :destroy, :index, :show]
      get '/page', to: 'pages#blank'
      get '/cohorts/:id/add-students', to: 'cohorts#add_students'
  end

  resources :cohorts, only: [:show, :index]
  resources :courses, only: [:show, :index]
  resources :instructors, only: [:show, :index]
  resources :students, only: [:show]

  scope '/student' do
  get '/home', to: 'students#home', as: :student_home
  get '/edit', to: 'students#edit'
  patch '/edit', to: 'students#update', as: :edit_student
  end

  scope '/instructor' do
  get '/home', to: 'instructors#home', as: :instructor_home
  get '/edit', to: 'instructors#edit'
  patch '/edit', to: 'instructors#update', as: :edit_instructor
  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  has_secure_password
  validates :first_name, :last_name, :education, presence: true
  validates :email, presence: true
  validates :enrolled, default: false
  validates :age, numericality: {less_than: 150, only_integer: true}, presence: true
  # has_and_belongs_to_many :cohorts
  belongs_to :cohorts, optional: true
  def full_credentials
  "#{last_name}, #{first_name} - #{id}"
  end
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < AdminsController

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(new_student_params)
    @student.email.downcase!
    @student.enrolled = false
    # @student.password = (0...8).map { (65 + rand(26)).chr }.join
    if @student.valid?
      @student.save
      redirect_to "/admin/students/#{@student.id}"
    else
      p @student.errors.messages
      flash.now[:danger] = "Invalid Credentials"
      render 'new'
    end
  end

  def index
  end

  def edit
    @student = Student.find_by_id(params[:id])
  end

  def update
    #   trying password confirm before change
  #   @admin = Admin.find_by_id(session[:user_id])
  # if @admin && @admin.authenticate(admin_confirm_params)

    @student = Student.find_by_id(params[:id])
    @student.update(edit_student_params)

    if @student.valid?
      redirect_to "/admin/students/#{@student.id}"
    else
      flash.now[:danger] = "Invalid Credentials"
      render 'edit'
    end

  end

  def show
    @student = Student.find_by_id(params[:id])
  end

  def destroy
    @student = Student.find_by_id(params[:id])
    respond_to do |format|
      format.js
    end
    @student.destroy
    # redirect_to new_admin_student_path
  end

  private
  def new_student_params
    params.require(:student).permit(:first_name, :last_name, :email, :enrolled, :age, :education, :password)
  end

  def edit_student_params
    params.require(:student).permit(:first_name, :last_name, :email, :enrolled, :age, :education)
  end

  def admin_confirm_params
    params.require(:admin).permit(:password)
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :check_user, only: [:home, :edit, :update]

  def show
    p session[:user_id]
    p session[:user]
    p params[:id]
    if session[:user] == 'student' && session[:user_id] == params[:id].to_i
    render '/student-home'

  else
    @student = Student.find(params[:id])
  end
end

  def home
    p session[:user_id]
    p session[:user]
    @student = Student.find_by_id(session[:user_id])
  end

  def edit
    @student = Student.find_by_id(session[:user_id])
  end

  def update
    @student = Student.find_by_id(session[:user_id])
    @student.update(edit_student_params)
    @student.email.downcase!
    if @student.valid?
      redirect_to student_home_path
    else
      flash[:danger] = "Invalid Credentials"
      render 'edit'
    end
  end

  private

  def edit_student_params
    params.require(:student).permit(:email, :password, :password_confirmation)
  end

  def check_user
    if session[:user] != "student"
      flash.now[:danger] = "You do not have to access this page"
      redirect_to '/login'
    end
  end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.erb
<h1>Edit</h1>
<p>Edit your info</p>
<div class="container main">

<%= form_for(@student, url: edit_student_url) do |f|%>

<%= f.label :email%>
<%= f.email_field :email%><br>
<%= f.label :password%>
<%= f.password_field :password%><br>

<%= f.label :password_confirmation%>
<%= f.password_field :password_confirmation%><br>

<%= f.submit "Submit"%>
<% end %>

</div>

app/views/students/home.html.erb
<h1>Welcome back <%= "#{@student.first_name} #{@student.last_name}"%></h1>
<div class="container main">
    <p><b>First name:</b> <%= @student.first_name%></p>

   <p><b>Last name:</b> <%= @student.last_name%></p>
  <p><b>Email:</b> <%= @student.email%></p>
  <p><b>Enrolled:</b> <%= @student.enrolled.to_s%></p>
  <p><b>Age:</b> <%= @student.age%></p>
  <p><b>Education:</b> <%= @student.education%></p>
  <p><b>Cohorts:</b> <%= @student.first_name%></p>

    <p>
      <a href=<%= "/student/edit"%>>
        <i class="fas fa-user-edit"></i>
      </a>
    </p>
</div>

app/views/students/new.html.erb
<h1>Students#new</h1>

<%= form_for(@student,url: create_student_url) do |f|%>
<%= f.label :first_name, "First Name"%>
<%= f.text_field :first_name%><br>
<%= f.label :last_name, "Last Name"%>
<%= f.text_field :last_name%><br>
<%= f.label :email%>
<%= f.email_field :email%><br>
<%= f.label :password%>
<%= f.password_field :password%><br>
<%= f.label :education, "Education Level"%>
<%= f.select(:education) do %>
  <% [['Highschool','Highschool'], ['College'], ['Masters'], ['PhD']].each do |c| -%>
    <%= content_tag(:option, c.first, value: c.last) %>
  <% end %>
  <% end%><br>
<%= f.label :age%>
<%= f.number_field :age%><br>
<%= f.submit "Submit"%>
<% end %>

app/views/students/show.html.erb
<h1><%= "#{@student.first_name} #{@student.last_name}"%></h1>
<p>Student info</p>
<div class="container main">
    <p><b>First name:</b> <%= @student.first_name%></p>

   <p><b>Last name:</b> <%= @student.last_name%></p>
  <p><b>Email:</b> <%= @student.email%></p>
  <p><b>Enrolled:</b> <%= @student.enrolled.to_s%></p>
  <p><b>Age:</b> <%= @student.age%></p>
  <p><b>Education:</b> <%= @student.education%></p>
  <!-- <p><b>Cohorts:</b> <%= @student.first_name%></p> -->

    <p>
      <a href=<%= "/student/edit"%>>
        <i class="fas fa-user-edit"></i>
      </a>
    </p>
</div>