config/routes.rb
Rails.application.routes.draw do
  match "/" => redirect("/login"), via:[:get]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # resources :admins

  namespace :admin do
      resources :students, only: [:new, :create, :index, :edit, :update, :destroy, :show]
      resources :instructors, only: [:new, :create, :edit, :update, :destroy, :index, :show]
      resources :cohorts, only: [:new, :create, :edit, :update, :destroy, :index, :show]
      resources :courses, only: [:new, :create, :edit, :update, :destroy, :index, :show]
      get '/page', to: 'pages#blank'
      get '/cohorts/:id/add-students', to: 'cohorts#add_students'
  end

  resources :cohorts, only: [:show, :index]
  resources :courses, only: [:show, :index]
  resources :instructors, only: [:show, :index]
  resources :students, only: [:show]

  scope '/student' do
  get '/home', to: 'students#home', as: :student_home
  get '/edit', to: 'students#edit'
  patch '/edit', to: 'students#update', as: :edit_student
  end

  scope '/instructor' do
  get '/home', to: 'instructors#home', as: :instructor_home
  get '/edit', to: 'instructors#edit'
  patch '/edit', to: 'instructors#update', as: :edit_instructor
  end




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  has_secure_password
  validates :first_name, :last_name, :education, presence: true
  validates :active, default: false
  validates :email, presence: true
  validates :age, numericality:{ less_than: 150, only_integer: true},presence: true
  validates :salary, numericality: { greater_than: 0, only_integer: true}, presence: true
  # has_and_belongs_to_many :cohorts
  has_many :cohorts
  def full_credentials
  "#{last_name}, #{first_name} - #{id}"
  end
end

app/controllers/admin/instructors_controller.rb
class Admin::InstructorsController < AdminsController


  def show
      @instr = Instructor.find_by_id(params[:id])
  end

  def new
    @instr = Instructor.new
  end

  def create
    @instr = Instructor.new(new_instr_params)
    @instr.email.downcase!
      if @instr.valid?
        @instr.save
        redirect_to "/admin/instructors/#{@instr.id}"
      else
        p @instr.errors.messages
        flash.now[:danger] = "Invalid Credentials"
        render 'new'
      end
  end

  def index

  end

  def destroy
    @instr = Instructor.find_by_id(params[:id])
    respond_to do |format|
      format.js
    end
    @instr.destroy
  end

  def edit
    @instr = Instructor.find_by_id(params[:id])
  end

  def update
    @instr = Instructor.find_by_id(params[:id])
    @instr.update(edit_instr_params)
      if @instr.valid?
        redirect_to "/admin/instructors/#{@instr.id}"
      else
        flash.now[:danger] = "Invalid Credentials"
        render 'edit'
      end
  end

  private

  def edit_instr_params
    params.require(:instructor).permit(:first_name, :last_name, :age, :salary, :education, :email)
  end

  def new_instr_params
    params.require(:instructor).permit(:first_name, :last_name, :age, :salary, :education, :email, :password)
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :check_user, only: [:home, :edit, :update]

  def index
    @instructors = Instructor.all
  end


  def show
    if session[:user] == 'instructor' && session[:user_id] == params[:id].to_i
    redirect_to '/instructor/home'
    else
    @instr = Instructor.find(params[:id])
    end
  end

  def home
    @instr = Instructor.find_by_id(session[:user_id])
  end

  def edit
    @instr = Instructor.find_by_id(session[:user_id])
  end

  def update
    @instr = Instructor.find_by_id(session[:user_id])
    @instr.update(edit_instr_params)
    @instr.email.downcase!
    if @instr.valid?
      redirect_to instructor_home_path
    else
      flash[:danger] = "Invalid Credentials"
      render 'edit'
    end
  end

  private

  def edit_instr_params
    params.require(:instructor).permit(:email, :password, :password_confirmation)
  end


  def check_user
    if session[:user] != "instructor"
      flash.now[:danger] = "You do not have to access this page"
      redirect_to '/login'
    end
  end

end

app/helpers/instructors_helper.rb
module InstructorsHelper
  def require_login
    if session[:user] = nil
      flash[:error] = "You must be logged in to access this page"
      redirect_to '/login'
    end
  end
end

app/views/instructors/edit.html.erb
<h1>Edit</h1>
<p>Edit your info</p>
<div class="container main">

<%= form_for(@instr, url: edit_instructor_url) do |f|%>

<%= f.label :email%>
<%= f.email_field :email%><br>
<%= f.label :password%>
<%= f.password_field :password%><br>
<%= f.label :password_confirmation%>
<%= f.password_field :password_confirmation%><br>


<%= f.submit "Submit"%>
<% end %>

</div>

app/views/instructors/home.html.erb
<h1>Welcome back <%= "#{@instr.first_name} #{@instr.last_name}"%></h1>
<div class="container main">
  <p>First name: <%= @instr.first_name%></p>

  <p>Last name: <%= @instr.last_name%></p>
  <p>Email: <%= @instr.email%></p>
  <p>Active: <%= @instr.active.to_s%></p>
  <p>Age: <%= @instr.age%></p>
  <p>Education: <%= @instr.education%></p>
  <p>Salary: <%= @instr.salary%></p>
  <!-- <p>Cohorts: <%= @instr.cohorts.count%></p> -->
    <p>
      <a href=<%= "/instructor/edit"%>>
        <i class="fas fa-user-edit"></i>
      </a>
    </p>
</div>

app/views/instructors/index.html.erb
<h1>Instructors</h1>
<p>Our Instructors</p>
<div class="container">

  <div class="row">
    <div class="col-md-3">
      <b>FIRST NAME</b>
    </div>
    <div class="col-md-3">
      <b>LAST NAME</b>
    </div>
    <div class="col-md-3">
      <b>EMAIL</b>
    </div>

    <div class="col-md-3">
      <b>ACTIVE</b>
    </div>

  </div>
  </div>

<div class="main overflow-auto">

<% Instructor.all.each do |i|%>

<div id="<%=i.id%>"class="row shadow-sm p-3 mb-5 bg-white rounded">
  <div class="col-md-3 border-right">
    <%= link_to(i.first_name, "/instructors/#{i.id}")%>

  </div>
  <div class="col-md-3 border-right">
    <%= link_to(i.last_name, "/instructors/#{i.id}")%>

  </div>
  <div class="col-md-3 border-right">
    <%= link_to(i.email, "/instructors/#{i.id}")%>

  </div>

  <div class="col-md-3 border-right">
    <%= link_to(i.active.to_s, "/instructors/#{i.id}")%>

  </div>

</div>
<% end%>


</div>

app/views/instructors/new.html.erb
<h1>Instructors#new</h1>
<%= form_for(@instr, url: create_instructor_url) do |f|%>
<%= f.label :first_name, "First Name"%>
<%= f.text_field :first_name%><br>
<%= f.label :last_name, "Last Name"%>
<%= f.text_field :last_name%><br>
<%= f.label :email%>
<%= f.email_field :email%><br>
<%= f.label :password%>
<%= f.password_field :password%><br>
<%= f.label :education, "Education Level"%>
<%= f.select(:education) do %>
  <% [['Highschool','Highschool'], ['College'], ['Masters'], ['PhD']].each do |c| -%>
    <%= content_tag(:option, c.first, value: c.last) %>
  <% end %>
  <% end%><br>
<%= f.label :age%>
<%= f.number_field :age%><br>
<%= f.label :salary%>
<%= f.number_field :salary%><br>
<%= f.submit "Submit"%>
<% end %>

app/views/instructors/show.html.erb
<h1><%= "#{@instr.first_name} #{@instr.last_name}"%></h1>
<p>Instructor info</p>
<div class="container main">
  <p><b>First name:</b> <%= @instr.first_name%></p>

  <p><b>Last name:</b> <%= @instr.last_name%></p>
  <p><b>Email:</b> <%= @instr.email%></p>
  <p><b>Active:</b> <%= @instr.active.to_s%></p>
  <p><b>Education:</b> <%= @instr.education%></p>
  <!-- <p>Cohorts: <%= @instr.cohorts.count%></p> -->

</div>